version: 0.2

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing app dependencies...
      - npm install
      - sudo yum install -y yum-utils shadow-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
  pre_build:
    on-failure: ABORT
    commands:
      - echo Running tests
      - npm run test
  build:
    on-failure: ABORT
    commands:
      - echo Building and Deploying app
      - cd manifests; pwd; terraform init; terraform plan; terraform apply --auto-approve;
      # - echo Building app and deplo
      # - cd app && npm run build
  # post_build:
  #   on-failure: ABORT
  #   commands:
  #     - echo Hosting React app on AWS ECS
  #     - pwd
  #     - npm run-script deploy

cache:
  paths:
    - './node_modules/**/*'