version: 0.2

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing app dependencies...
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Running tests
      - npm run test
  build:
    on-failure: ABORT
    commands:
      - echo Building app
      - cd app && npm run build
  post_build:
    on-failure: ABORT
    commands:
      - echo Starting the React App
      - npm run start
cache:
  paths:
    - './node_modules/**/*'